---
- hosts: all
  become: yes
  tasks: 
  - name: in this tasks , i want install apache2 webservers 
    apt:
      name: apache2
      state: present
    when: ansible_os_family== "Debian"
  - name: in this, i want to start webservers
    service:
      name: apache2
      state: started
    when: ansible_os_family== "Debian" 
    